from datetime import datetime

from sqlmodel import Field, Relationship, SQLModel

from app.models.enums import MOState, WorkOrderState


class ManufacturingOrder(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    name: str = Field(default="", index=True)  # human ref e.g. MO-0001
    product_id: int = Field(foreign_key="product.id")
    bom_id: int | None = Field(default=None, foreign_key="bom.id")
    qty: float = 1.0
    state: MOState = Field(default=MOState.DRAFT, index=True)
    origin: str = ""  # e.g. "SO-0007" when auto-generated by procurement
    assignee_id: int | None = Field(default=None, foreign_key="user.id")
    created_by_id: int | None = Field(default=None, foreign_key="user.id")
    created_at: datetime = Field(default_factory=datetime.utcnow)

    work_orders: list["WorkOrder"] = Relationship(
        back_populates="mo",
        sa_relationship_kwargs={"cascade": "all, delete-orphan"},
    )


class WorkOrder(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    mo_id: int = Field(foreign_key="manufacturingorder.id", index=True)
    operation_name: str
    duration_mins: int = 0
    work_center: str = ""
    sequence: int = 1
    state: WorkOrderState = Field(default=WorkOrderState.PENDING)

    mo: ManufacturingOrder | None = Relationship(back_populates="work_orders")
