from datetime import datetime

from sqlmodel import Field, Relationship, SQLModel

from app.models.enums import PurchaseOrderState


class PurchaseOrder(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    name: str = Field(default="", index=True)  # human ref e.g. PO-0001
    partner_id: int = Field(foreign_key="partner.id")
    state: PurchaseOrderState = Field(default=PurchaseOrderState.DRAFT, index=True)
    origin: str = ""  # e.g. "SO-0007" when auto-generated by procurement
    order_date: datetime = Field(default_factory=datetime.utcnow)
    expected_receipt_date: datetime | None = None
    created_by_id: int | None = Field(default=None, foreign_key="user.id")
    created_at: datetime = Field(default_factory=datetime.utcnow)

    lines: list["PurchaseOrderLine"] = Relationship(
        back_populates="order",
        sa_relationship_kwargs={"cascade": "all, delete-orphan"},
    )


class PurchaseOrderLine(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    purchase_order_id: int = Field(foreign_key="purchaseorder.id", index=True)
    product_id: int = Field(foreign_key="product.id")
    qty: float = 1.0
    qty_received: float = 0.0
    unit_price: float = 0.0

    order: PurchaseOrder | None = Relationship(back_populates="lines")
